### PR TITLE
initial commit Aufgabenblatt 4

### PR DESCRIPTION
**Pull request by JavaBoii**
Erstellen einer Main Datei
`lololollolol`

### CODE REVIEW

**Comment by JavaBoii** [comment]
bruh

**Comment by Rookwie** [comment]
I have no idea what's this about

**Comment by JavaBoii** [comment]
it was a test. I wanted to see how the merge draft looked like. And it was the correct one

**Comment by Rookwie** [comment]
Idk what I'm doing here, no questions pls

**Pull request merged**
